"""bootstrap platform identity tenancy rbac invitations billing

Revision ID: 21c252f1123a
Revises:
Create Date: 2026-08-01 20:43:47.267164+00:00

THE BASELINE SCHEMA (spec §3). One migration, no history before it.

=============================================================================
FOUR CLASSES OF TABLE, AND WHY EACH GETS DIFFERENT TREATMENT
=============================================================================

  1. PLATFORM tables -- `permissions`, `plans`, `platform_admins`,
     `platform_audit_logs`, `webhook_events`.
     GRANT only, NO RLS. Each is structurally incapable of belonging to one
     organization: `plans` is served to the unauthenticated pricing page and
     referenced by every tenant at once; `platform_admins` belong to no org;
     `permissions` is a catalog of what the software can do; a webhook arrives
     before we know which org it concerns. Enabling RLS would make them invisible
     to every request, since there is no `organization_id` to compare.

  2. IDENTITY tables -- `users`, `sessions`, `password_reset_tokens`,
     `email_verification_tokens`.
     GRANT only, NO RLS, for two reasons. First, a chicken-and-egg problem: to set
     `app.current_org_id` we need the org from the token, but to issue a token we
     must first find the user -- and a policy comparing against an unset GUC matches
     zero rows, so login would be structurally impossible. Second, and more
     fundamentally, one human genuinely belongs to no single organization: a teacher
     employed by two client school groups is one person with one password
     (spec decision D4).

  3. `organizations` -- RLS keyed on its own PRIMARY KEY, not on an
     `organization_id` column, which would be circular.

  4. TENANT tables -- everything else. RLS on `organization_id` (spec decision D3).

  Plus `role_permissions`, which carries no tenant column of its own: it inherits
  containment from `role_id`, whose table IS policy-protected, so a row here is
  unreachable without first passing the policy on `roles`. A redundant tenant column
  would only create the possibility of it disagreeing with the role's.

=============================================================================
THE POLICY IS ASYMMETRIC: READ WIDER THAN WRITE
=============================================================================
  USING      -> organization_id = current org  OR  is_platform_admin = 'on'
  WITH CHECK -> organization_id = current org             (no admin escape)

  A platform admin may READ across tenants for support and billing; they may not
  WRITE into one. See `alembic/rls.py` for the full reasoning.

REVIEW CHECKLIST for future migrations:
  [ ] Does downgrade() actually reverse upgrade()? Test it locally.
  [ ] New tenant table? It needs organization_id NOT NULL + setup_tenant_table().
      Autogenerate does NOT emit RLS statements -- you must add them by hand.
  [ ] Adding a NOT NULL column to a populated table? add nullable -> backfill ->
      set NOT NULL. A single-step add locks the table and fails on existing rows.
  [ ] Creating an index on a large table? postgresql_concurrently=True.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from alembic.rls import (
    APP_ROLE,
    grant_app_role,
    setup_organizations_table,
    setup_platform_table,
    setup_tenant_table,
    teardown_tenant_table,
)
from sqlalchemy.dialects import postgresql

revision: str = "21c252f1123a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Tables governed by the standard `organization_id` policy.
TENANT_TABLES: tuple[str, ...] = (
    "schools",
    "roles",
    "memberships",
    "invitations",
    "audit_logs",
    "subscriptions",
    "subscription_events",
    "invoices",
    "payments",
    "organization_usage",
    "classes",
    "sections",
    "students",
)

# Outside tenancy by design -- see the module docstring.
PLATFORM_TABLES: tuple[str, ...] = (
    "permissions",
    "plans",
    "platform_admins",
    "platform_audit_logs",
    "webhook_events",
    "users",
    "sessions",
    "password_reset_tokens",
    "email_verification_tokens",
)


def upgrade() -> None:
    _create_prerequisites()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("resource", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "min_scope",
            sa.Enum(
                "org",
                "school",
                name="min_scope",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_dangerous", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_permissions")),
    )
    op.create_index(
        "ix_permissions_category_resource", "permissions", ["category", "resource"], unique=False
    )
    op.create_table(
        "plans",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("marketing_tagline", sa.String(length=200), nullable=True),
        sa.Column("price_monthly", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("price_yearly", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("trial_days", sa.Integer(), nullable=False),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(price_monthly IS NULL OR price_monthly >= 0) AND (price_yearly IS NULL OR price_yearly >= 0)",
            name=op.f("ck_plans_prices_non_negative"),
        ),
        sa.CheckConstraint("trial_days >= 0", name=op.f("ck_plans_trial_days_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_plans_code")),
    )
    op.create_index(
        "ix_plans_is_public_is_active_sort_order",
        "plans",
        ["is_public", "is_active", "sort_order"],
        unique=False,
    )
    op.create_table(
        "platform_admins",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=64), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_admins")),
        sa.UniqueConstraint("email", name=op.f("uq_platform_admins_email")),
    )
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "suspended",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lockout_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(
        "uq_users_email_active",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "webhook_events",
        sa.Column("gateway", sa.String(length=32), nullable=False),
        sa.Column("gateway_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
    )
    op.create_index(
        "ix_webhook_events_processed_at", "webhook_events", ["processed_at"], unique=False
    )
    op.create_index(
        "uq_webhook_events_gateway_event",
        "webhook_events",
        ["gateway", "gateway_event_id"],
        unique=True,
    )
    op.create_table(
        "email_verification_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_verification_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_verification_tokens")),
    )
    op.create_index(
        "ix_email_verification_tokens_expires_at",
        "email_verification_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_tokens_user_id"),
        "email_verification_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_email_verification_tokens_token_hash",
        "email_verification_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "trialing",
                "active",
                "past_due",
                "over_limit",
                "suspended",
                "cancelled",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("billing_email", postgresql.CITEXT(), nullable=True),
        sa.Column("tax_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_organizations_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations_deleted_at"), "organizations", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_owner_user_id"), "organizations", ["owner_user_id"], unique=False
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_index(
        "ix_organizations_status_created_at",
        "organizations",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
    )
    op.create_index(
        "ix_password_reset_tokens_expires_at", "password_reset_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_index(
        "uq_password_reset_tokens_token_hash", "password_reset_tokens", ["token_hash"], unique=True
    )
    op.create_table(
        "organization_usage",
        sa.Column("schools_count", sa.Integer(), nullable=False),
        sa.Column("students_count", sa.Integer(), nullable=False),
        sa.Column("staff_count", sa.Integer(), nullable=False),
        sa.Column("custom_roles_count", sa.Integer(), nullable=False),
        sa.Column("storage_used_mb", sa.Integer(), nullable=False),
        sa.Column("recomputed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "schools_count >= 0 AND students_count >= 0 AND staff_count >= 0 AND custom_roles_count >= 0 AND storage_used_mb >= 0",
            name=op.f("ck_organization_usage_counts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_usage_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_usage")),
    )
    op.create_index(
        op.f("ix_organization_usage_organization_id"),
        "organization_usage",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_organization_usage_organization_id",
        "organization_usage",
        ["organization_id"],
        unique=True,
    )
    op.create_table(
        "platform_audit_logs",
        sa.Column("actor_admin_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("target_organization_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_admin_id"],
            ["platform_admins.id"],
            name=op.f("fk_platform_audit_logs_actor_admin_id_platform_admins"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_organization_id"],
            ["organizations.id"],
            name=op.f("fk_platform_audit_logs_target_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_audit_logs")),
    )
    op.create_index(
        op.f("ix_platform_audit_logs_actor_admin_id"),
        "platform_audit_logs",
        ["actor_admin_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_created_at_desc",
        "platform_audit_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_audit_logs_target_organization_id"),
        "platform_audit_logs",
        ["target_organization_id"],
        unique=False,
    )
    op.create_table(
        "schools",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("academic_year_start_month", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                "archived",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "academic_year_start_month BETWEEN 1 AND 12",
            name=op.f("ck_schools_academic_year_start_month_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_schools_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schools")),
    )
    op.create_index(op.f("ix_schools_deleted_at"), "schools", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_schools_organization_id"), "schools", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_schools_organization_id_status", "schools", ["organization_id", "status"], unique=False
    )
    op.create_index(
        "uq_schools_organization_id_code",
        "schools",
        ["organization_id", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_schools_organization_id_slug",
        "schools",
        ["organization_id", "slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "trialing",
                "active",
                "past_due",
                "suspended",
                "cancelled",
                "expired",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "billing_cycle",
            sa.Enum(
                "monthly",
                "yearly",
                name="billing_cycle",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gateway", sa.String(length=32), nullable=True),
        sa.Column("gateway_customer_ref", sa.String(length=128), nullable=True),
        sa.Column("gateway_subscription_ref", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_subscriptions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
            name=op.f("fk_subscriptions_plan_id_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_index(
        "ix_subscriptions_current_period_end", "subscriptions", ["current_period_end"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_organization_id"), "subscriptions", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_plan_id"), "subscriptions", ["plan_id"], unique=False)
    op.create_index("ix_subscriptions_status", "subscriptions", ["status"], unique=False)
    op.create_index(
        "uq_subscriptions_organization_id", "subscriptions", ["organization_id"], unique=True
    )
    op.create_table(
        "classes",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("level >= 0", name=op.f("ck_classes_level_non_negative")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_classes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_classes_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
        sa.UniqueConstraint("school_id", "level", name="uq_classes_school_id_level"),
        sa.UniqueConstraint("school_id", "name", name="uq_classes_school_id_name"),
    )
    op.create_index(op.f("ix_classes_deleted_at"), "classes", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_classes_organization_id"), "classes", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_classes_school_id"), "classes", ["school_id"], unique=False)
    op.create_index("ix_classes_school_id_level", "classes", ["school_id", "level"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("amount_subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount_tax", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "open",
                "paid",
                "void",
                "uncollectible",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gateway_ref", sa.String(length=128), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_total >= 0 AND amount_subtotal >= 0",
            name=op.f("ck_invoices_amounts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invoices_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_invoices_subscription_id_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("number", name=op.f("uq_invoices_number")),
    )
    op.create_index(
        op.f("ix_invoices_organization_id"), "invoices", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_invoices_organization_id_created",
        "invoices",
        ["organization_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("ix_invoices_status", "invoices", ["status"], unique=False)
    op.create_index(
        op.f("ix_invoices_subscription_id"), "invoices", ["subscription_id"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_editable", sa.Boolean(), nullable=False),
        sa.Column("permissions_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_roles_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_roles_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False)
    op.create_index(
        "ix_roles_organization_id_school_id",
        "roles",
        ["organization_id", "school_id"],
        unique=False,
    )
    op.create_index(op.f("ix_roles_school_id"), "roles", ["school_id"], unique=False)
    op.create_index(
        "uq_roles_organization_id_school_id_code",
        "roles",
        ["organization_id", "school_id", "code"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "subscription_events",
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("from_plan_id", sa.UUID(), nullable=True),
        sa.Column("to_plan_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_plan_id"],
            ["plans.id"],
            name=op.f("fk_subscription_events_from_plan_id_plans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_subscription_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_events_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_plan_id"],
            ["plans.id"],
            name=op.f("fk_subscription_events_to_plan_id_plans"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_events")),
    )
    op.create_index(
        "ix_subscription_events_org_created",
        "subscription_events",
        ["organization_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_events_organization_id"),
        "subscription_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_events_subscription_id"),
        "subscription_events",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "invitations",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "expired",
                "revoked",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_user_id", sa.UUID(), nullable=True),
        sa.Column("resent_count", sa.Integer(), nullable=False),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accepted_user_id"],
            ["users.id"],
            name=op.f("fk_invitations_accepted_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_invitations_invited_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invitations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_invitations_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_invitations_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
    )
    op.create_index("ix_invitations_expires_at", "invitations", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_invitations_organization_id"), "invitations", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_invitations_organization_id_status",
        "invitations",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_invitations_role_id"), "invitations", ["role_id"], unique=False)
    op.create_index(op.f("ix_invitations_school_id"), "invitations", ["school_id"], unique=False)
    op.create_index(
        "uq_invitations_pending_email",
        "invitations",
        ["organization_id", "school_id", "email"],
        unique=True,
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index("uq_invitations_token_hash", "invitations", ["token_hash"], unique=True)
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "suspended",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_memberships_invited_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_memberships_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_memberships_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
    )
    op.create_index(op.f("ix_memberships_deleted_at"), "memberships", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_memberships_organization_id_school_id",
        "memberships",
        ["organization_id", "school_id"],
        unique=False,
    )
    op.create_index(op.f("ix_memberships_role_id"), "memberships", ["role_id"], unique=False)
    op.create_index(op.f("ix_memberships_school_id"), "memberships", ["school_id"], unique=False)
    op.create_index(
        "ix_memberships_user_id_live",
        "memberships",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_memberships_user_organization_school",
        "memberships",
        ["user_id", "organization_id", "school_id"],
        unique=True,
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "payments",
        sa.Column("invoice_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "succeeded",
                "failed",
                "refunded",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("gateway", sa.String(length=32), nullable=False),
        sa.Column("gateway_ref", sa.String(length=128), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_payments_invoice_id_invoices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_payments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_gateway_ref"), "payments", ["gateway_ref"], unique=False)
    op.create_index(op.f("ix_payments_invoice_id"), "payments", ["invoice_id"], unique=False)
    op.create_index(
        op.f("ix_payments_organization_id"), "payments", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_payments_organization_id_created",
        "payments",
        ["organization_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_code"],
            ["permissions.code"],
            name=op.f("fk_role_permissions_permission_code_permissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_code", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "sections",
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("class_teacher_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "capacity IS NULL OR capacity > 0", name=op.f("ck_sections_capacity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_sections_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["class_teacher_id"],
            ["users.id"],
            name=op.f("fk_sections_class_teacher_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sections_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_sections_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("school_id", "class_id", "name", name="uq_sections_school_class_name"),
    )
    op.create_index(op.f("ix_sections_class_id"), "sections", ["class_id"], unique=False)
    op.create_index(
        op.f("ix_sections_class_teacher_id"), "sections", ["class_teacher_id"], unique=False
    )
    op.create_index(op.f("ix_sections_deleted_at"), "sections", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_sections_organization_id"), "sections", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_sections_school_id"), "sections", ["school_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_membership_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_membership_id"],
            ["memberships.id"],
            name=op.f("fk_audit_logs_actor_membership_id_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_audit_logs_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_organization_id_created_at",
        "audit_logs",
        ["organization_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_school_id"), "audit_logs", ["school_id"], unique=False)
    op.create_index(
        "ix_audit_logs_school_id_created_at",
        "audit_logs",
        ["school_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("platform_admin_id", sa.UUID(), nullable=True),
        sa.Column("membership_id", sa.UUID(), nullable=True),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(user_id IS NOT NULL) <> (platform_admin_id IS NOT NULL)",
            name=op.f("ck_sessions_exactly_one_principal"),
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_sessions_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["platform_admin_id"],
            ["platform_admins.id"],
            name=op.f("fk_sessions_platform_admin_id_platform_admins"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index("ix_sessions_expires_at", "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_family_id"), "sessions", ["family_id"], unique=False)
    op.create_index(
        "ix_sessions_family_id_revoked_at", "sessions", ["family_id", "revoked_at"], unique=False
    )
    op.create_index(op.f("ix_sessions_membership_id"), "sessions", ["membership_id"], unique=False)
    op.create_index(
        op.f("ix_sessions_platform_admin_id"), "sessions", ["platform_admin_id"], unique=False
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_index(
        "ix_sessions_user_id_revoked_at", "sessions", ["user_id", "revoked_at"], unique=False
    )
    op.create_index(
        "uq_sessions_refresh_token_hash", "sessions", ["refresh_token_hash"], unique=True
    )
    op.create_table(
        "students",
        sa.Column("admission_number", sa.String(length=32), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum(
                "male",
                "female",
                "other",
                name="gender",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("guardian_name", sa.String(length=160), nullable=True),
        sa.Column("guardian_phone", sa.String(length=32), nullable=True),
        sa.Column("guardian_email", sa.String(length=320), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=160), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=32), nullable=True),
        sa.Column("section_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "inactive",
                "graduated",
                "transferred",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("enrolled_on", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_students_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_students_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_students_section_id_sections"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint(
            "school_id", "admission_number", name="uq_students_school_id_admission_number"
        ),
    )
    op.create_index(op.f("ix_students_deleted_at"), "students", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_students_organization_id"), "students", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_students_school_id"), "students", ["school_id"], unique=False)
    op.create_index(
        "ix_students_school_id_section_id", "students", ["school_id", "section_id"], unique=False
    )
    op.create_index(
        "ix_students_school_id_status", "students", ["school_id", "status"], unique=False
    )
    op.create_index(op.f("ix_students_section_id"), "students", ["section_id"], unique=False)
    # ### end Alembic commands ###

    # -----------------------------------------------------------------------
    # Row-Level Security. Autogenerate never emits this -- it is added by hand,
    # and a tenant table that ships without it silently leaks every
    # organization's data to every other organization.
    # -----------------------------------------------------------------------
    setup_organizations_table()

    for table in TENANT_TABLES:
        setup_tenant_table(table)

    for table in PLATFORM_TABLES:
        setup_platform_table(table)

    # No tenant column of its own; containment comes from `roles`.
    grant_app_role("role_permissions")


def _create_prerequisites() -> None:
    """Extensions and the restricted application role.

    Duplicated from `scripts/init-db.sql` so a migration run against a database
    that never saw that script still produces a working schema -- CI, a fresh
    staging box, or a managed Postgres where the init hook does not exist. Every
    statement is IF NOT EXISTS or guarded, so running both is harmless.

    `citext` matters most: every email column depends on it, and without the
    extension the very first CREATE TABLE fails with an unhelpful type error.
    """
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # NOSUPERUSER + NOBYPASSRLS is the entire point. PostgreSQL exempts superusers
    # and table owners from RLS, so an application connecting as the owner would
    # have every policy below silently disabled.
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                CREATE ROLE {APP_ROLE} WITH LOGIN PASSWORD 'sms_app_password'
                    NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS INHERIT;
            END IF;
        END
        $$
        """
    )
    op.execute(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}")


def downgrade() -> None:
    # Policies must go before the tables they are attached to. Dropping a table
    # with a live policy works, but leaving a policy behind on a re-created table
    # does not -- CREATE POLICY would then fail with a duplicate name.
    for table in (*TENANT_TABLES, "organizations"):
        teardown_tenant_table(table)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_students_section_id"), table_name="students")
    op.drop_index("ix_students_school_id_status", table_name="students")
    op.drop_index("ix_students_school_id_section_id", table_name="students")
    op.drop_index(op.f("ix_students_school_id"), table_name="students")
    op.drop_index(op.f("ix_students_organization_id"), table_name="students")
    op.drop_index(op.f("ix_students_deleted_at"), table_name="students")
    op.drop_table("students")
    op.drop_index("uq_sessions_refresh_token_hash", table_name="sessions")
    op.drop_index("ix_sessions_user_id_revoked_at", table_name="sessions")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_platform_admin_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_membership_id"), table_name="sessions")
    op.drop_index("ix_sessions_family_id_revoked_at", table_name="sessions")
    op.drop_index(op.f("ix_sessions_family_id"), table_name="sessions")
    op.drop_index("ix_sessions_expires_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_audit_logs_school_id_created_at", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_school_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_organization_id_created_at", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_sections_school_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_organization_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_deleted_at"), table_name="sections")
    op.drop_index(op.f("ix_sections_class_teacher_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_class_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_table("role_permissions")
    op.drop_index("ix_payments_organization_id_created", table_name="payments")
    op.drop_index(op.f("ix_payments_organization_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_gateway_ref"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(
        "uq_memberships_user_organization_school",
        table_name="memberships",
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_memberships_user_id_live",
        table_name="memberships",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_memberships_school_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_role_id"), table_name="memberships")
    op.drop_index("ix_memberships_organization_id_school_id", table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_deleted_at"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index("uq_invitations_token_hash", table_name="invitations")
    op.drop_index(
        "uq_invitations_pending_email",
        table_name="invitations",
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_invitations_school_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_role_id"), table_name="invitations")
    op.drop_index("ix_invitations_organization_id_status", table_name="invitations")
    op.drop_index(op.f("ix_invitations_organization_id"), table_name="invitations")
    op.drop_index("ix_invitations_expires_at", table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_subscription_events_subscription_id"), table_name="subscription_events")
    op.drop_index(op.f("ix_subscription_events_organization_id"), table_name="subscription_events")
    op.drop_index("ix_subscription_events_org_created", table_name="subscription_events")
    op.drop_table("subscription_events")
    op.drop_index(
        "uq_roles_organization_id_school_id_code",
        table_name="roles",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("ix_roles_school_id"), table_name="roles")
    op.drop_index("ix_roles_organization_id_school_id", table_name="roles")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_invoices_subscription_id"), table_name="invoices")
    op.drop_index("ix_invoices_status", table_name="invoices")
    op.drop_index("ix_invoices_organization_id_created", table_name="invoices")
    op.drop_index(op.f("ix_invoices_organization_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index("ix_classes_school_id_level", table_name="classes")
    op.drop_index(op.f("ix_classes_school_id"), table_name="classes")
    op.drop_index(op.f("ix_classes_organization_id"), table_name="classes")
    op.drop_index(op.f("ix_classes_deleted_at"), table_name="classes")
    op.drop_table("classes")
    op.drop_index("uq_subscriptions_organization_id", table_name="subscriptions")
    op.drop_index("ix_subscriptions_status", table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_plan_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_organization_id"), table_name="subscriptions")
    op.drop_index("ix_subscriptions_current_period_end", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(
        "uq_schools_organization_id_slug",
        table_name="schools",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_schools_organization_id_code",
        table_name="schools",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_schools_organization_id_status", table_name="schools")
    op.drop_index(op.f("ix_schools_organization_id"), table_name="schools")
    op.drop_index(op.f("ix_schools_deleted_at"), table_name="schools")
    op.drop_table("schools")
    op.drop_index(
        op.f("ix_platform_audit_logs_target_organization_id"), table_name="platform_audit_logs"
    )
    op.drop_index("ix_platform_audit_logs_created_at_desc", table_name="platform_audit_logs")
    op.drop_index(op.f("ix_platform_audit_logs_actor_admin_id"), table_name="platform_audit_logs")
    op.drop_table("platform_audit_logs")
    op.drop_index("uq_organization_usage_organization_id", table_name="organization_usage")
    op.drop_index(op.f("ix_organization_usage_organization_id"), table_name="organization_usage")
    op.drop_table("organization_usage")
    op.drop_index("uq_password_reset_tokens_token_hash", table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index("ix_password_reset_tokens_expires_at", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index("ix_organizations_status_created_at", table_name="organizations")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_owner_user_id"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_deleted_at"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index("uq_email_verification_tokens_token_hash", table_name="email_verification_tokens")
    op.drop_index(
        op.f("ix_email_verification_tokens_user_id"), table_name="email_verification_tokens"
    )
    op.drop_index("ix_email_verification_tokens_expires_at", table_name="email_verification_tokens")
    op.drop_table("email_verification_tokens")
    op.drop_index("uq_webhook_events_gateway_event", table_name="webhook_events")
    op.drop_index("ix_webhook_events_processed_at", table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(
        "uq_users_email_active", table_name="users", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_table("platform_admins")
    op.drop_index("ix_plans_is_public_is_active_sort_order", table_name="plans")
    op.drop_table("plans")
    op.drop_index("ix_permissions_category_resource", table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
