"""add classes sections and students

Revision ID: 65f26101542e
Revises: 75f594204a1c
Create Date: 2026-07-20 08:41:29.904956+00:00

REVIEW CHECKLIST -- confirm before merging:
  [ ] Does downgrade() actually reverse upgrade()? Test it locally.
  [ ] New tenant table? It needs school_id NOT NULL + ENABLE ROW LEVEL SECURITY
      + a tenant_isolation POLICY. Autogenerate does NOT emit RLS statements --
      you must add them by hand (see the helpers in alembic/rls.py).
  [ ] Adding a NOT NULL column to a populated table? Use the three-step pattern:
      add nullable -> backfill -> set NOT NULL. A single-step add locks the table
      and fails on existing rows.
  [ ] Creating an index on a large table? Use postgresql_concurrently=True and
      set transaction_per_migration=False for that revision -- CREATE INDEX takes
      an exclusive lock that blocks writes for the duration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from alembic.rls import disable_tenant_rls, setup_tenant_table


revision: str = "65f26101542e"
down_revision: str | None = "75f594204a1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classes",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("level >= 0", name=op.f("ck_classes_level_non_negative")),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_classes_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
        sa.UniqueConstraint("school_id", "level", name="uq_classes_school_id_level"),
        sa.UniqueConstraint("school_id", "name", name="uq_classes_school_id_name"),
    )
    op.create_index(op.f("ix_classes_deleted_at"), "classes", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_classes_school_id"), "classes", ["school_id"], unique=False)
    op.create_index("ix_classes_school_id_level", "classes", ["school_id", "level"], unique=False)
    op.create_table(
        "sections",
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("class_teacher_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "capacity IS NULL OR capacity > 0", name=op.f("ck_sections_capacity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_sections_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["class_teacher_id"],
            ["users.id"],
            name=op.f("fk_sections_class_teacher_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_sections_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("school_id", "class_id", "name", name="uq_sections_school_class_name"),
    )
    op.create_index(op.f("ix_sections_class_id"), "sections", ["class_id"], unique=False)
    op.create_index(
        op.f("ix_sections_class_teacher_id"), "sections", ["class_teacher_id"], unique=False
    )
    op.create_index(op.f("ix_sections_deleted_at"), "sections", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_sections_school_id"), "sections", ["school_id"], unique=False)
    op.create_table(
        "students",
        sa.Column("admission_number", sa.String(length=32), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum(
                "male",
                "female",
                "other",
                name="gender",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("guardian_name", sa.String(length=160), nullable=True),
        sa.Column("guardian_phone", sa.String(length=32), nullable=True),
        sa.Column("guardian_email", sa.String(length=320), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=160), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=32), nullable=True),
        sa.Column("section_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "inactive",
                "graduated",
                "transferred",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("enrolled_on", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_students_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_students_section_id_sections"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint(
            "school_id", "admission_number", name="uq_students_school_id_admission_number"
        ),
    )
    op.create_index(op.f("ix_students_deleted_at"), "students", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_students_school_id"), "students", ["school_id"], unique=False)
    op.create_index(
        "ix_students_school_id_section_id", "students", ["school_id", "section_id"], unique=False
    )
    op.create_index(
        "ix_students_school_id_status", "students", ["school_id", "status"], unique=False
    )
    op.create_index(op.f("ix_students_section_id"), "students", ["section_id"], unique=False)
    # ### end Alembic commands ###

    # --- Row-Level Security (NOT autogenerated -- added by hand) --------------
    # Every one of these tables carries school_id, so each needs the standard
    # school_id-based tenant policy plus DML grants for the sms_app role. Without
    # this block the tables would be readable across tenants: the app role would
    # have no grants at all (immediate breakage), and any role that did have grants
    # would see every school's rows (silent, permanent data leak).
    setup_tenant_table("classes")
    setup_tenant_table("sections")
    setup_tenant_table("students")


def downgrade() -> None:
    # Drop policies before the tables, mirroring upgrade() in reverse.
    disable_tenant_rls("students")
    disable_tenant_rls("sections")
    disable_tenant_rls("classes")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_students_section_id"), table_name="students")
    op.drop_index("ix_students_school_id_status", table_name="students")
    op.drop_index("ix_students_school_id_section_id", table_name="students")
    op.drop_index(op.f("ix_students_school_id"), table_name="students")
    op.drop_index(op.f("ix_students_deleted_at"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_sections_school_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_deleted_at"), table_name="sections")
    op.drop_index(op.f("ix_sections_class_teacher_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_class_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index("ix_classes_school_id_level", table_name="classes")
    op.drop_index(op.f("ix_classes_school_id"), table_name="classes")
    op.drop_index(op.f("ix_classes_deleted_at"), table_name="classes")
    op.drop_table("classes")
    # ### end Alembic commands ###
