"""bootstrap tenancy and auth

Revision ID: 75f594204a1c
Revises:
Create Date: 2026-07-20 04:17:51.224618+00:00

THE FOUNDATION MIGRATION -- creates the four tables every later module builds on.

RLS is applied BY HAND here, because autogenerate cannot infer it. Two shapes:

  * `schools` gets a *self-referential* policy (`id = <tenant>`), not the usual
    `school_id = <tenant>` one -- a school IS the tenant, so it has no school_id.
    `setup_tenant_table()` assumes a `school_id` column, so the policy is written
    out in full below instead.

  * `users`, `otp_codes`, `refresh_tokens` deliberately get NO RLS at all. Login,
    forgot-password and refresh all run BEFORE a tenant is known, so an RLS policy
    comparing against an unset GUC would match zero rows and make authentication
    structurally impossible. They receive table-level DML grants only; the
    application-layer `school_id` filter in UserRepository is their scoping. See the
    long docstring in app/modules/auth/models.py for the full rationale.

REVIEW CHECKLIST -- confirmed:
  [x] downgrade() reverses upgrade() (policy + RLS dropped before the table).
  [x] schools: NOT a school_id table -> hand-written id-based policy + FORCE RLS.
  [x] auth tables: intentionally outside RLS, grants only.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from alembic.rls import APP_ROLE, SUPER_ADMIN_GUC, TENANT_GUC, grant_app_role

revision: str = "75f594204a1c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schools",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending_approval",
                "active",
                "suspended",
                "cancelled",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "plan",
            sa.Enum(
                "trial",
                "basic",
                "standard",
                "premium",
                name="plan",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subscription_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_students", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schools")),
    )
    op.create_index(op.f("ix_schools_deleted_at"), "schools", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_schools_slug"), "schools", ["slug"], unique=True)
    op.create_index(
        "ix_schools_status_created_at", "schools", ["status", "created_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "super_admin",
                "school_admin",
                "teacher",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_verification",
                "active",
                "suspended",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("two_factor_enabled", sa.Boolean(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_users_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index("ix_users_school_id_role", "users", ["school_id", "role"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(
        "uq_users_email_active",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "otp_codes",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "signup_verify",
                "password_reset",
                "login_2fa",
                "email_change",
                name="purpose",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_otp_codes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_codes")),
    )
    op.create_index(
        "ix_otp_codes_email_purpose_created",
        "otp_codes",
        ["email", "purpose", "created_at"],
        unique=False,
    )
    op.create_index("ix_otp_codes_expires_at", "otp_codes", ["expires_at"], unique=False)
    op.create_index(op.f("ix_otp_codes_user_id"), "otp_codes", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("jti", name="uq_refresh_tokens_jti"),
    )
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_index(
        "ix_refresh_tokens_user_id_revoked_at",
        "refresh_tokens",
        ["user_id", "revoked_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # ================================================================= GRANTS
    # The application role owns nothing and creates nothing; it receives explicit
    # table-level DML here. RLS (below, schools only) then governs *which rows*.
    for table in ("schools", "users", "otp_codes", "refresh_tokens"):
        grant_app_role(table)

    # =========================================================== RLS: schools
    # Self-referential tenant policy: a caller may see/write the ONE school row
    # whose id equals their bound tenant, or ANY row when acting as super admin.
    # NULLIF(current_setting(...), '') yields NULL (not an error) when the GUC is
    # unset, so `id = NULL` simply matches nothing rather than raising.
    school_predicate = (
        f"(id = NULLIF(current_setting('{TENANT_GUC}', true), '')::uuid"
        f" OR current_setting('{SUPER_ADMIN_GUC}', true) = 'on')"
    )
    op.execute("ALTER TABLE schools ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE schools FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON schools "
        f"FOR ALL TO {APP_ROLE} "
        f"USING {school_predicate} "
        f"WITH CHECK {school_predicate}"
    )
    # users / otp_codes / refresh_tokens: NO RLS by design -- see module docstring.


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON schools")
    op.execute("ALTER TABLE schools NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE schools DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refresh_tokens_user_id_revoked_at", table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_otp_codes_user_id"), table_name="otp_codes")
    op.drop_index("ix_otp_codes_expires_at", table_name="otp_codes")
    op.drop_index("ix_otp_codes_email_purpose_created", table_name="otp_codes")
    op.drop_table("otp_codes")
    op.drop_index(
        "uq_users_email_active", table_name="users", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index("ix_users_school_id_role", table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_schools_status_created_at", table_name="schools")
    op.drop_index(op.f("ix_schools_slug"), table_name="schools")
    op.drop_index(op.f("ix_schools_deleted_at"), table_name="schools")
    op.drop_table("schools")
    # ### end Alembic commands ###
